### ISSUE TITLE
Weather anomaly matviews broken

### ISSUE THREAD

**Issue by rod-glover** [pacificclimate/pycds#64]

**Comment by rod-glover** [comment]
```
$ manage-views.py -d 'postgresql://crmp@monsoon/crmp' refresh all
2020-10-01 15:48:32,307 - pycds.manage_views - INFO: Refresh 'crmp.daily_max_temperature_mv'
Traceback (most recent call last):
  File "/storage/home/crmprtd/env_3.1.5/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/storage/home/crmprtd/env_3.1.5/lib64/python3.6/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedFunction: function crmp.effective_day(timestamp without time zone, unknown, timescale) does not exist
LINE 1: ...ry_id AS history_id, good_obs.vars_id AS vars_id, crmp.effec...
```

Problem appears to be that arguments to `effective_day` must be cast to appropriate types. Specifically `extremum` and `freq` both cast to `VARCHAR`. There are tests for the same function `manage_views` that the command line calls, and they pass. Why?

**Comment by rod-glover** [comment]
Some progress. Now getting:

```
2020-10-08 14:22:11,631 - pycds.manage_views - INFO: Refresh 'crmp.daily_max_temperature_mv'
2020-10-08 15:12:09,887 - pycds.manage_views - INFO: Refresh 'crmp.daily_min_temperature_mv'
2020-10-08 15:53:15,475 - pycds.manage_views - INFO: Refresh 'crmp.monthly_average_of_daily_max_temperature_mv'
daily_temperature_extremum('max').selectable SELECT crmp.meta_history.history_id AS history_id, good_obs.vars_id AS vars_id, crmp.effective_day(good_obs.time, CAST(:param_1 AS VARCHAR), CAST(crmp.meta_history.freq AS VARCHAR)) AS obs_day, max(good_obs.datum) AS statistic, sum(CASE crmp.meta_history.freq WHEN :param_2 THEN :param_3 WHEN :param_4 THEN :param_5 WHEN :param_6 THEN :param_7 END) AS data_coverage 
FROM (SELECT crmp.obs_raw.obs_raw_id AS id, crmp.obs_raw.obs_time AS time, crmp.obs_raw.mod_time AS mod_time, crmp.obs_raw.datum AS datum, crmp.obs_raw.vars_id AS vars_id, crmp.obs_raw.history_id AS history_id 
FROM crmp.obs_raw LEFT OUTER JOIN crmp.obs_raw_native_flags ON crmp.obs_raw.obs_raw_id = crmp.obs_raw_native_flags.obs_raw_id LEFT OUTER JOIN crmp.meta_native_flag ON crmp.meta_native_flag.native_flag_id = crmp.obs_raw_native_flags.native_flag_id LEFT OUTER JOIN crmp.obs_raw_pcic_flags ON crmp.obs_raw.obs_raw_id = crmp.obs_raw_pcic_flags.obs_raw_id LEFT OUTER JOIN crmp.meta_pcic_flag ON crmp.meta_pcic_flag.pcic_flag_id = crmp.obs_raw_pcic_flags.pcic_flag_id GROUP BY crmp.obs_raw.obs_raw_id 
HAVING NOT bool_or(coalesce(crmp.meta_native_flag.discard, :coalesce_1)) AND NOT bool_or(coalesce(crmp.meta_pcic_flag.discard, :coalesce_2))) AS good_obs JOIN crmp.meta_vars ON crmp.meta_vars.vars_id = good_obs.vars_id JOIN crmp.meta_history ON crmp.meta_history.history_id = good_obs.history_id 
WHERE crmp.meta_vars.standard_name = :standard_name_1 AND crmp.meta_vars.cell_method IN (:cell_method_1, :cell_method_2, :cell_method_3) AND crmp.meta_history.freq IN (:freq_1, :freq_2, :freq_3) GROUP BY crmp.meta_history.history_id, good_obs.vars_id, obs_day
daily_temperature_extremum('min').selectable SELECT crmp.meta_history.history_id AS history_id, good_obs.vars_id AS vars_id, crmp.effective_day(good_obs.time, CAST(:param_1 AS VARCHAR), CAST(crmp.meta_history.freq AS VARCHAR)) AS obs_day, min(good_obs.datum) AS statistic, sum(CASE crmp.meta_history.freq WHEN :param_2 THEN :param_3 WHEN :param_4 THEN :param_5 WHEN :param_6 THEN :param_7 END) AS data_coverage 
FROM (SELECT crmp.obs_raw.obs_raw_id AS id, crmp.obs_raw.obs_time AS time, crmp.obs_raw.mod_time AS mod_time, crmp.obs_raw.datum AS datum, crmp.obs_raw.vars_id AS vars_id, crmp.obs_raw.history_id AS history_id 
FROM crmp.obs_raw LEFT OUTER JOIN crmp.obs_raw_native_flags ON crmp.obs_raw.obs_raw_id = crmp.obs_raw_native_flags.obs_raw_id LEFT OUTER JOIN crmp.meta_native_flag ON crmp.meta_native_flag.native_flag_id = crmp.obs_raw_native_flags.native_flag_id LEFT OUTER JOIN crmp.obs_raw_pcic_flags ON crmp.obs_raw.obs_raw_id = crmp.obs_raw_pcic_flags.obs_raw_id LEFT OUTER JOIN crmp.meta_pcic_flag ON crmp.meta_pcic_flag.pcic_flag_id = crmp.obs_raw_pcic_flags.pcic_flag_id GROUP BY crmp.obs_raw.obs_raw_id 
HAVING NOT bool_or(coalesce(crmp.meta_native_flag.discard, :coalesce_1)) AND NOT bool_or(coalesce(crmp.meta_pcic_flag.discard, :coalesce_2))) AS good_obs JOIN crmp.meta_vars ON crmp.meta_vars.vars_id = good_obs.vars_id JOIN crmp.meta_history ON crmp.meta_history.history_id = good_obs.history_id 
WHERE crmp.meta_vars.standard_name = :standard_name_1 AND crmp.meta_vars.cell_method IN (:cell_method_1, :cell_method_2, :cell_method_3) AND crmp.meta_history.freq IN (:freq_1, :freq_2, :freq_3) GROUP BY crmp.meta_history.history_id, good_obs.vars_id, obs_day
Traceback (most recent call last):
  File "/home/rglover/code/pycds/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    self.dialect.do_execute(
  File "/home/rglover/code/pycds/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedFunction: function crmp.daysinmonth(timestamp without time zone) does not exist
LINE 1: ...g_daily_extreme_temperature.total_data_coverage / crmp.DaysI...
                                                             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

**Comment by rod-glover** [comment]
Same deal, cast arguments. Ugly, but works.
